package com.example.demo.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2019-12-19T11:12:17.613+08:00
 * Generated source version: 3.2.11
 *
 */
@WebServiceClient(name = "DemoService",
                  wsdlLocation = "http://127.0.0.1:8888/services/TestService?wsdl",
                  targetNamespace = "http://service.demo.example.com")
public class DemoService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.demo.example.com", "DemoService");
    public final static QName DemoServiceImplPort = new QName("http://service.demo.example.com", "DemoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8888/services/TestService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8888/services/TestService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DemoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DemoService
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public DemoService getDemoServiceImplPort() {
        return super.getPort(DemoServiceImplPort, DemoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoService
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public DemoService getDemoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DemoServiceImplPort, DemoService.class, features);
    }

}
